### PR TITLE
Simplify routing

### PR DESCRIPTION
**Pull request by Pilchie**

### CODE REVIEW

**Comment by Pilchie** [comment]
@rynowak this is what I wanted to do, but with this clicking in the NavMenu doesn't seem to be updating the repo params the way I expect it to and I have to refresh :(

**Comment by rynowak** [comment]
You need to use `OnParametersSetAsync()` instead for this case. If we can reuse your component instance we will. We're cheap like that.  https://docs.microsoft.com/en-us/aspnet/core/blazor/lifecycle?view=aspnetcore-3.1#after-parameters-are-set

**Comment by rynowak** [comment]
Did this work thne?

**Comment by Pilchie** [comment]
Yep.  Thanks for the help!  https://github.com/Pilchie/YouHaveIssues/pull/10/commits/3e999d4ce31621517ed9bb1991afb4c7d1a90c28 was what I needed.

**Pull request merged**
