### PR TITLE
Add support for more repos, and 'area: ' as well as 'area-'

### PR DESCRIPTION
**Pull request by Pilchie**

### CODE REVIEW

**Comment by Pilchie** [comment]
@rynowak / @danroth27 / @SteveSandersonMS- can you help me with Blazor routing sometime?  Ideally, you'd be able to go to any `https://youhaveissues.azurewebsites.net/<org>/<repo>` and have it operate on it, but I don't understand routing.

**Comment by rynowak** [comment]
> but I don't understand routing.

Can you explain what the term means? It's not super clear to me what you're asking for help with.

**Comment by Pilchie** [comment]
Take a look at the Parameters of RepoView.razor. Could I just make that the only page? If so, how do I handle the case where people don’t supply the Parameters?

**Comment by rynowak** [comment]
> If so, how do I handle the case where people don’t supply the Parameters?

There's a few options depending on how you want to factor the pages.

---

If you used a route like `@page "/{org}/{repo}"

Then the page would only match when both parameters are supplied. You would use a different page to match the root URL, and that page could show a UI to select the org and repo.

---

Or if you want, you could have a single page for the whole app with multiple routes.

```
@page "/"
@page "/{org}/{repo}"
```

Then you show the UI if those parameters get a null value.

---

Does that make sense?

**Pull request merged**
